### PR TITLE
Handle migrating from WP SEO to Yoast SEO

### LINKED ISSUE #56: Task: Create WP SEO -> Yoast SEO migration scripts
Migrate any existing WP SEO data into Yoast SEO. This includes both global settings and per-post meta.

**Acceptance Criteria:**
- [x] Create a migration script hooked to `wp altis migrate` (e.g. `wp altis migrate seo`)
  - [x] Migrate WP SEO option data
  - [x] Migrate WP SEO postmeta

**Dev Notes**
> how does WP SEO store the custom title, description and keywords for a post? How can those be migrated?

Both WP SEO and Yoast SEO store that information in post meta, and each have comparable meta keys for that data. Yoast uses a formula for the SEO title (e.g. `%%title%% %%page%% %%sep%% %%sitename%%`). We could either default to this or migrate existing data in the WP SEO `_meta_title` field to `_yoast_wpseo_title`, which is the Yoast equivalent and only added if the title was manually changed from the default pattern.

Screen Shot 2021-05-10 at 12 37 13 PM

Probably what makes the most sense is to migrate the meta data over if it exists -- WP SEO also has default patterns which would get migrated over as part of the migration process, so the most important information here is the meta descriptions and SEO keywords, which would be unique for each post.

### PR DESCRIPTION
**Pull request by roborourke**
Fixes #56

Handles the title options settings and post meta.

### CODE REVIEW

**Comment by roborourke** [comment]
Just need to do some more testing but I think is ready more or less.

**Comment by roborourke** [comment]
Good to go here, tested all the title settings and post meta migration.

**Review by jazzsequence — COMMENTED** [review]
A couple questions before merging but I don't think any really block anything:

* This covers Yoast SEO...what about other parts of our SEO module? E.g. Redirects. Will/should that be handled in separate tickets for those plugins?
* This seems like it could be a potentially long script on large sites. Have you tested/timed a full migration? 
* I don't see any docs on the migration. Should that be handled in a separate ticket or part of the definition of done for this one?

**Comment by roborourke** [comment]
It’s a good question but as we’re not bundling Yoast Premium yet it’s perhaps not essential but a nice to have. I’ll look at how easy that is when I’m back.

It could indeed be a long running script if there’s a lot of customised posts but to be honest I haven’t seen a site making heavy use of SEO post meta that wasn’t already using Yoast. Worth having a further look though in case the meta keys exist with empty values as that would take forever.

i didn’t think about docs specifically, figured that would come under the existing docs for the migrate command and what will be in the upgrade guide. Which is something we should write up ASAP 🤔

**Comment by jazzsequence** [comment]
All that sounds good to me. I will create a ticket for at least the seo migration docs (unless we have an existing ticket for migration docs generally that I could tack that onto) and add a note in the redirect ticket that a migration script for that might be needed as well.

I will approve & merge after I do that stuff.

**Comment by jazzsequence** [comment]
Redirect migration is already part of #59. 
Created new documentation issue for docs for `wp migrate` generally humanmade/altis-documentation#251

**Review by jazzsequence — APPROVED** [review]

**Pull request merged**
