### PR TITLE
Improvements to migrate command

### LINKED ISSUE #149: Migrate command processes every post object on the site
While upgrading to Altis v9, running `altis migrate` in a local environment with a recently refreshed database from an Altis project with approximately 19k published posts caused 361,017 post objects to be processed while "Migrating legacy SEO settings" and took almost 2 hours to run to completion. The query within the `migrate_wpseo_to_yoast` function is returning every single post object on the site, including revisions and oembed caches.

The site in question has been using Yoast Premium for years, and never relied on the legacy Altis SEO module. If I query the database directly, I see no meta keys matching our target `$old` values in the [`meta_mapping` object](https://github.com/humanmade/altis-seo/blob/master/inc/namespace.php#L511-L515). _e.g._,

```
select count(*) from wp_postmeta where meta_key="_meta_title";
+----------+
| count(*) |
+----------+
|        0 |
+----------+
```

The reason things are taking so long to run is the `meta_query` we execute within that `migrate_wpseo_to_yoast()` function:

```php
	'meta_query' => [
		'relation' => 'OR',
		[
			'meta_key' => '_meta_title',
			'meta_compare' => 'EXISTS',
		],
		[
			'meta_key' => '_meta_description',
			'meta_compare' => 'EXISTS',
		],
		[
			'meta_key' => '_meta_keywords',
			'meta_compare' => 'EXISTS',
		],
	],
```
Note that we're using `meta_key` and `meta_compare` in the nested arrays. If I am reading the [wp meta query docs](https://developer.wordpress.org/reference/classes/wp_meta_query/#accepted-arguments) properly, those keys are only accepted in the `meta_query` array itself, and nested arrays should be using `key` and `compare`, _e.g._

```php
	[
		'key' => '_meta_keywords',
		'compare' => 'EXISTS',
	],
```

Because of this difference between the expected arguments and what we are providing, I believe the current query is stripping all meta query comparisons and returning every post on every site. This will result in a LOT of unnecessary processing while upgrading to Altis 9, because the migration routine then goes through the entire site and tries to find each of those three keys on every single post object (none of which have them), to no actual benefit.

You can validate that the `meta_key` is being ignored and returning all posts by trying this query locally in `wp shell`:
```php
// Handle post meta.
$posts_query_args = [
    'post_type' => 'post',
    'post_status' => 'any',
    'posts_per_page' => 0,
    'fields' => 'ids',
    'suppress_filters' => true,
    'meta_query' => [
        'relation' => 'OR',
        [
            'meta_key' => '2014 SUBARU IMPREZA WRX Hatch, Premium trim, 32k miles',
            'meta_compare' => 'EXISTS',
        ],
    ],
];
$posts = new WP_Query( $posts_query_args );

// Will log however many posts you have.
WP_CLI::log( $posts->found_posts );
```

Switching these meta parameters to `key` and `compare` may not fix the issue, because I made those changes locally and started running that query 30 minutes ago and it still hasn't completed. A triple-barrel EXISTS `meta_compare` on a medium-to-large site appears to be paralyzingly slow. (In my testing, only querying for a single `EXISTS` meta query at a time was any kind of fast.) However, I suspect that if it does complete, it will correctly detect that no posts in the site actually have these keys present.

This is a pretty big issue with the Altis 9 upgrade path.

Acceptance criteria:

- [ ] Only posts with old WP SEO meta keys present get processed when running the Altis SEO migration routine.
- [ ] The migration command runs in a reasonable amount of time

### PR DESCRIPTION
**Pull request by roborourke**
Fixes #149 

Also prevents updating existing Yoast data.

### CODE REVIEW

**Review by kadamwhite — CHANGES_REQUESTED** [review]
While this corrects the issue, this command is going to take a very, very long time to run. It ran for over 30m locally when I made the same change myself, and I finally gave up.

If we did our first check using three separate meta queries, then only proceed with the expensive one if we actually have posts, that would mitigate things. But the triple-barreled OR is prohibitively slow in my testing.

**Comment by kadamwhite** [comment]
I restarted the query using this branch to test timing. Two hours and fifteen minutes in, the first `count => 0` query to find the number of posts is still running. The new query is worse on a site of this scale (360k post objects) than just running the original logic on every single post object. It's an untenable query.

**Comment by Sephsekla** [comment]
Can this be handled by a flag passed to the cli command? I still think it's worth having the option to query for posts with any of the meta set to deal with certain sites, but maybe the default behaviour should revert back to how it was before https://github.com/humanmade/altis-seo/pull/145 with the option to query more thoroughly if necessary.

**Comment by roborourke** [comment]
I think we're over-egging it at that point. Sigh. I guess it should be a separate command, the `altis migrate` output can just recommend you might need to run this other command e.g. `altis migrate seo`.

**Comment by kadamwhite** [comment]
The fastest way to do it would be to loop three times,

- look for any posts with the first key
  - if there are results, page through
  - for every item, if it has any of the three keys (check all of them), migrate that data
- repeat with the second key
- repeat with the third key

You'll probably have a much shorter loop for the third option. Any individual meta query for EXISTS on a single value seems to go pretty quickly.

**Review by kadamwhite — APPROVED** [review]
:raised_hands: Amazing, @roborourke ! Noting that we might need to update the v9 upgrade guide after this lands, but I can confirm it worked as advertised for me.

**Pull request merged**
