### PR TITLE
Handle loading Yoast Premium from vendor directory

### LINKED ISSUE #99: Yoast Premium installation broken with Altis v8
Yoast premium when installed via composer adds the free version of Yoast SEO as a dependency and attempts to load it from the same directory / location.

We need to determine how best to load Yoast SEO Premium alongside our modifications for the installation location and loading for the Yoast SEO free version.

### PR DESCRIPTION
**Pull request by roborourke**
Fixes #99

### CODE REVIEW

**Comment by kadamwhite** [comment]
@roborourke I'll test this out. However, are we worried that this will increase the maintenance burden over time? Since this increases the complexity of the integration and effectively means we need to validate the bootstrap procedure of two plugins, I'd imagine it locks each version of Altis to a specific range of Yoast plugins if any internal APIs change.

Because it's installed via Composer I suppose the likelihood of a breaking change getting in by mistake is lower due to version ranges, and I generally trust the Yoast team to follow good practices around versioning, but I wanted to open the topic for discussion.

**Comment by kadamwhite** [comment]
This whitescreens the site if Yoast was previously active prior to the update,
```
[01-Sep-2021 14:58:42 UTC] PHP Notice:  Constant WPSEO_PREMIUM_VERSION already defined in /usr/src/app/vendor/altis/seo/inc/namespace.php on line 135
[01-Sep-2021 14:58:42 UTC] PHP Fatal error:  Cannot redeclare YoastSEOPremium() (previously declared in /usr/src/app/content/plugins/wordpress-seo-premium/src/functions.php:20) in /usr/src/app/vendor/yoast/wordpress-seo-premium/src/functions.php on line 17
[01-Sep-2021 14:58:42 UTC] PHP Notice:  Constant WPSEO_PREMIUM_VERSION already defined in /usr/src/app/vendor/altis/seo/inc/namespace.php on line 135
[01-Sep-2021 14:58:42 UTC] PHP Fatal error:  Cannot redeclare YoastSEOPremium() (previously declared in /usr/src/app/content/plugins/wordpress-seo-premium/src/functions.php:20) in /usr/src/app/vendor/yoast/wordpress-seo-premium/src/functions.php on line 17
```
The plugin gets left behind in `content/plugins` the same way `wordpress-seo` did when it shadowed this bug during upgrade testing

**Comment by kadamwhite** [comment]
@roborourke Looks like it's working. This does however _restore_ the need to clear the deploy cache prior to deploying v8, if we need to delete that folder, correct?

**Comment by roborourke** [comment]
We're locking ourselves to a specific range of all dependencies anyway, so we won't be using WPSEO 17 with v8 at all. We already have maintenance burdens when it comes to updating ElasticPress, WordPress core, etc... so it's no different to that really. All about cost vs benefit, and Yoast SEO provides a lot of benefit.

**Review by kadamwhite — APPROVED** [review]
Let's give it a go. Will it include the v17 requirement when we backport, or will that go back to 16.9 for v8?

**Comment by kadamwhite** [comment]
I see your note about versions you left while I was reviewing. Sounds good, fire at will

**Comment by roborourke** [comment]
> @roborourke Looks like it's working. This does however restore the need to clear the deploy cache prior to deploying v8, if we need to delete that folder, correct?

Hm, yeah maybe the first time if premium was already installed to the plugins directory in cloud. It's a one-off though.

**Comment by kadamwhite** [comment]
It would also need to be cleared if you previously used Yoast SEO free version via composer, since that would also have been installed to plugins/

**Comment by roborourke** [comment]
Right yeah, that should have been in the upgrade guide.

**Pull request merged**
